#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ZSH help
unalias run-help
autoload run-help
export HELPDIR=/usr/local/share/zsh/help
# fpath=(/usr/local/share/zsh-completions $fpath)

# NVM
export NVM_DIR="${ZDOTDIR:-$HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# RBENV
eval "$(rbenv init -)"

# BEST!
eval "$(thefuck --alias)"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export CCP_HOME=/Users/ukotu01/Dev/ticketmaster/ccp/tmol-web-spring

export TM_API="pTAf3X1DA6XCHjaQaw0WmlgcA0j1r32C"
export HOMEBREW_GITHUB_API_TOKEN="e16b872b0c2a065bbd2f02dea584d3c8601d5d01"
