#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ZSH help
unalias run-help
autoload run-help
export HELPDIR=/usr/local/share/zsh/help
# fpath=(/usr/local/share/zsh-completions $fpath)

# NVM
export NVM_DIR="${ZDOTDIR:-$HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# Docker environment variables
eval "$(docker-machine env default)"

# Temporary hack to get round libsass issues
export UV_THREADPOOL_SIZE=64

# BEST!
eval "$(thefuck --alias)"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
